import {
  AlertTriangle,
  Brain,
  BriefcaseBusiness,
  Building2,
  CalendarClock,
  CheckCircle2,
  CircleDollarSign,
  ClipboardCheck,
  FileArchive,
  Gauge,
  LayoutDashboard,
  MessagesSquare,
  PackageCheck,
  Settings,
  TrendingUp,
  Users,
  WandSparkles,
} from "lucide-react";

export const navItems = [
  { label: "Dashboard", href: "/", icon: LayoutDashboard },
  { label: "Tenders", href: "/tenders", icon: BriefcaseBusiness },
  { label: "AI Analysis", href: "/ai-analysis", icon: Brain },
  { label: "Tender Chat", href: "/tender-chat", icon: MessagesSquare },
  { label: "Qualification", href: "/qualification", icon: CheckCircle2 },
  { label: "Compliance", href: "/compliance", icon: ClipboardCheck },
  { label: "Estimation", href: "/estimation", icon: CircleDollarSign },
  { label: "Manpower", href: "/manpower", icon: Users },
  { label: "Asset Register", href: "/assets", icon: PackageCheck },
  { label: "PPM Planner", href: "/ppm-planner", icon: CalendarClock },
  { label: "Proposal Generator", href: "/proposals", icon: WandSparkles },
  { label: "Risk Register", href: "/risk-register", icon: AlertTriangle },
  { label: "SLA & KPI", href: "/sla-kpi", icon: Gauge },
  { label: "Suppliers", href: "/suppliers", icon: Building2 },
  { label: "Reports", href: "/reports", icon: TrendingUp },
  { label: "Export Center", href: "/exports", icon: FileArchive },
  { label: "Settings", href: "/settings", icon: Settings },
];
